### ISSUE TITLE
Add '.each' method 

### ISSUE THREAD

**Issue by dgroup** [dgroup/enumerable4j#33]
https://ruby-doc.org/core-2.6/Enumerator.html#method-i-each
https://mixandgo.com/learn/how-to-use-ruby-each

**Comment by FuncGuy** [comment]
i would like to work on this can you please give the example what is the usage of '.each' method

**Comment by dykov** [comment]
@dgroup , should it work like a Java `.forEach` method?

**Comment by dgroup** [comment]
Yes, the same but it should also return *this* instead of void
