### ISSUE TITLE
Add '.uniq' method

### ISSUE THREAD

**Issue by dgroup** [dgroup/enumerable4j#39]
https://ruby-doc.org/core-2.6/Enumerable.html#method-i-uniq

**Comment by FuncGuy** [comment]
i would like to work on this

**Comment by dykov** [comment]
Proposed in #63

**Comment by dykov** [comment]
implemented in #65

**Comment by dgroup** [comment]
@rultor merge

**Comment by dykov** [comment]
@dgroup , we have Unique class already

**Comment by dykov** [comment]
Added in #81
